$('.pictures').owlCarousel({
    loop:true,
    margin:2,
    stagePadding:100,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})

$('.sponsors').owlCarousel({
    loop:true,
    margin:2,
    nav:true,
    responsive:{
        0:{
            items:5
        },
        600:{
            items:1
        },
        1000:{
            items:6
        }
    }
})

$('.category-items').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:5
        },
        600:{
            items:4
        },
        1000:{
            items:4
        }
    }
})