$('.pictures').owlCarousel({
    loop:true,
    margin:2,
    stagePadding:100,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})